before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

test:
  image: tud_ifk/miniconda-cidefault
  stage: test
  script:
    - conda env create -f environment_dev.yml
    - source activate lbsntransform
    # test dev install
    - pip install -e . --no-dependencies
    # create badges
    - pylint --output-format=text lbsntransform | tee pylint.txt || pylint-exit $?
    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
    - echo "Pylint score was $score"
    - anybadge -l pylint --value=$score --file=pylint.svg 2=red 4=orange 9=yellow 10=green
    - anybadge -l pipeline --value=passing --file=pipeline.svg passing=green failing=red
    - pypi_version=$(pip search lbsntransform | cut -d "(" -f2 | cut -d ")" -f1 | sed -r "s/[latest]+//g")
    - echo "Pypi version was $pypi_version"
    - anybadge -l pypi --value="$pypi_version" --file=pypi.svg --color=green
  artifacts:
    paths:
      - pylint.svg
      - pypi.svg
      - pipeline.svg
  only:
  - master

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp pylint.svg .public
    - cp pipeline.svg .public
    - cp pypi.svg .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

