name: lbsntransform
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - pip
  - autopep8
  - emoji>=2.0.0
  - numpy
  - protobuf<=4.21.9
  - psycopg2
  - pylint
  - shapely<2.0.0
  - requests
  - bitarray
  - nltk
  - regex
  - pip:
    - pylint-exit
    - ppygis3
    - lbsnstructure>=1.0.3
    - geos

