name: lbsntransform
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - pip
  - emoji>=2.0.0
  - numpy
  - protobuf<=4.21.9
  - shapely
  - requests
  - nltk
  - psycopg2
  - regex
  - pip:
    - lbsnstructure>=0.5.1
    - ppygis3>=0.4
    - geos

