name: lbsntransform
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - pip
  - emoji>=2.0.0
  - numpy
  - pycodestyle
  - protobuf<=3.19.4
  - psycopg2
  - pylint
  - shapely
  - requests
  - bitarray
  - nltk
  - regex
  - pip:
    - pylint-exit
    - ppygis3
    - lbsnstructure>=0.5.1
    - geos

