name: lbsntransform
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - pip
  - emoji>=2.0.0
  - numpy
  - protobuf>=4.21.9,<5
  - shapely<2.0.0
  - requests
  - nltk
  - psycopg2
  - regex
  - pip:
    - lbsnstructure>=1.2.0
    - ppygis3>=0.4
    - geos

