name: lbsntransform
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - pip
  - emoji>=0.5.1
  - geos
  - numpy
  - protobuf
  - shapely
  - requests
  - pip:
    - lbsnstructure>=0.5.0
    - ppygis3>=0.4

